import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'

import Search from '@/components/Search/Search'
import RecentSearches from '@/components/RecentSearches/RecentSearches'
import SearchSuggestions from '@/components/SearchSuggestions/SearchSuggestions'

import styles from '@/styles/Home.module.css'


export default function Home() {
  const [search, setSearch] = useState('')
  const [suggestions, setSuggestions] = useState<{ text: string }[]>([])
  const router = useRouter()


  useEffect(() => {
    getSugestions()
  }, [search])

  const getSugestions = async () => {
    const res = await fetch(`/api/sugestions?query=${search}`);
    const result = await res.json();
    setSuggestions(result.data.suggestions)
  }

  const handleSearch = (query: string) => {
    const local: string[] = JSON.parse(window.localStorage.getItem('searched-items') ?? '[]')

    if (!local.includes(query)) {
      local.push(query)
      window.localStorage.setItem('searched-items', JSON.stringify(local))
    }
    router.push(`kategori?q=${query}`)
  }


  return (
    <>
      <Head>
        <title>MatSpar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <Search search={search} setSearch={setSearch} handleSearch={handleSearch} />
        </header>
        {suggestions?.length && search ?
          <SearchSuggestions suggestions={suggestions} handleSearch={handleSearch} />
          : <RecentSearches handleSearch={handleSearch} />}
      </main>
    </>
  )
}
