import Head from 'next/head'
import Search from '@/components/Search/Search'

import styles from '@/styles/Home.module.css'
import { useState } from 'react'
import RecentSearches from '@/components/RecentSearches/RecentSearches'
import axios from 'axios'
import SearchSuggestions from '@/components/SearchSuggestions/SearchSuggestions'
import { useRouter } from 'next/router'

// const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const [search, setSearch] = useState('')
  const [suggestions, setSuggestions] = useState({ suggestions: [] })
  const router = useRouter()


  const getSugestions = () => {
    let headersList = {
      "Accept": "*/*",
      "User-Agent": "Thunder Client (https://www.thunderclient.com)"
    }

    let reqOptions = {
      url: "https://api.matspar.se/autocomplete?query=cola",
      method: "GET",
      headers: headersList,
    }

    axios.request(reqOptions).then(function (response) {
      setSuggestions(response.data);
    })
  }

  const handleSearch = (query: string) => {
    router.push(`kategori?q=${query}`)
  }




  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>
          <Search search={search} setSearch={setSearch} handleSearch={getSugestions} />
        </header>
        {search ?
          <SearchSuggestions suggestions={suggestions.suggestions} handleSearch={handleSearch} />
          : <RecentSearches handleSearch={handleSearch} />}
      </main>
    </>
  )
}
